[project]
name = "Pointnuker_SOR"
version = "0.2.1"
description = "Statistical Outlier Removal for 3DGS point clouds, extracted from PointNuker"
authors = [{name = "PointNuker / LichtFeld Plugin Port By bb6"}]
dependencies = ["open3d", "numpy", "pyvista", "pyvistaqt", "PySide6" ]

[tool.lichtfeld]
hot_reload = true
plugin_api = ">=1,<2"
lichtfeld_version = ">=0.4.2"
required_features = []
